name: "[api] build"
on: 
    push:
        branches: [main]
        paths:
            - "backend/api/**"
            - ".github/workflows/build-api-image.yml"
    
    workflow_dispatch:

env:
    IMAGE_NAME: api_image
    REGISTRY: ghcr.io

jobs:
    build: 
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./backend/api/JavaApi

        steps: 
          - name: checkout
            uses: actions/checkout@v4
          - name: Log into registry
            run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

          - name: Build the package
            run: ./mvnw package -Dnative

          - name: Build and push image
            run: |
                IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

                # Strip git ref prefix from version
                VERSION=$(echo "${{ github.ref }}" | sed -e 's/[\/-]/_/g')

                # tag
                TAG=$IMAGE_ID:$VERSION

                # Change all uppercase to lowercase
                TAG=$(echo $TAG | tr '[A-Z]' '[a-z]')

                echo TAG=$TAG

                # Build the Docker image
                docker build -f src/main/docker/Dockerfile.native -t $TAG .

                # Docker Push
                docker push $TAG
